### ISSUE TITLE
Error in main

### ISSUE THREAD

**Issue by Kishaihd** [KellyReddington/TumblrLikesDownloader#1]
I'm getting the following error when I run the script:

`Traceback (most recent call last):
  File "download.py", line 45, in <module>
    main()
  File "download.py", line 36, in main
    dirname = info['user']['name']
KeyError: 'user' `

**Comment by Marogian** [comment]
Just in case anyone else is trying to figure this out, go here to get your token_key and token_secret keys to go in the tumblr_keys.py file:

https://api.tumblr.com/console

Enter in your consumer key and secret and it'll give you the tokens. Script then works.
